Adding a semicolon at the end
A semicolon at the end is needed to prevent "Uncaught TypeError: (intermediate value)(…) is not a function" in situations where md5.js is bundled with other libraries.